server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  forward-headers-strategy: framework

spring:
  profiles:
    default: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_SECRET}
            redirect-uri: "{baseUrl}/oauth/callback/{registrationId}"
            scope:
              - email
              - public_profile
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "{baseUrl}/oauth/callback/{registrationId}"
            scope:
              - email
              - profile

springdoc:
  swagger-ui:
    persist-authorization: true

jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}

social-login:
  redirect: ${SOCIAL_LOGIN_REDIRECT}

cors:
  origin:
    development: ${CORS_ORIGIN_DEVELOPMENT}
    production: ${CORS_ORIGIN_PRODUCTION}

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ap-northeast-2
