server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update

jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}

cors:
  origin:
    development: ${CORS_ORIGIN_DEVELOPMENT}
    production: ${CORS_ORIGIN_PRODUCTION}
