spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_SECRET}
            redirect-uri: "https://{baseHost}{basePort}/oauth/callback/{registrationId}"
            scope:
              - email
              - public_profile
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "https://{baseHost}{basePort}/oauth/callback/{registrationId}}"
            scope:
              - email
              - profile

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
